name: java-spring-sqs-plugin
description: AWS SQS plugin para projetos Java + Spring Boot
display-name: java-spring-sqs-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Versão da biblioteca software.amazon.awssdk:sqs
    type: text
    name: sqs_version
    default: 2.16.18
    required: true
  - label: Pacote para classes de configuração. Ex - br.com.org.projeto.config
    type: text
    name: pacote_configuracao_sqs
    required: true
  - label: Nome da classe de configurações AWS
    type: text
    name: aws_config_class_name
    default: AwsConfiguration
  - label: Nome da classe de configurações SQS
    type: text
    name: sqs_config_class_name
    default: SqsConfiguration
  - label: Pacote para a classe producer. Ex - br.com.org.projeto.sqs
    type: text
    name: pacote_producer_sqs
    required: true
  - label: Nome da classe do Produtor SQS
    type: text
    name: sqs_produtor_class_name
    default: SqsPublisher

computed-inputs:   
  "pasta_configuracao_sqs": "src/main/java/{{inputs.pacote_configuracao_sqs | replace('.','/') | replace('-','')}}"
  "pasta_producer_sqs": "src/main/java/{{inputs.pacote_producer_sqs | replace('.','/') | replace('-','')}}"                       
  "pacote_configuracao_sqs": "{{inputs.pacote_configuracao_sqs | replace('-','')}}"
  "aws_config_class_name": "{{inputs.aws_config_class_name | replace('.','') | replace('-','')}}"
  "sqs_config_class_name": "{{inputs.sqs_config_class_name | replace('.','') | replace('-','')}}"
  "pacote_producer_sqs": "{{inputs.pacote_producer_sqs | replace('.','') | replace('-','')}}"
  "sqs_produtor_class_name": "{{inputs.sqs_produtor_class_name | replace('.','') | replace('-','')}}"


hooks:
  - type: edit
    trigger: after-render
    path: pom.xml          
    changes:
      - search:
          string: </dependencies>
          insert-before:
            snippet: snippets/lombok.xml
          when:
            not-exists-snippet: snippets/lombok.xml
  - type: edit
    trigger: after-render
    path: pom.xml          
    changes:
      - search:
          string: </dependencies>
          insert-before:
            snippet: snippets/sqs.xml
          when:
            not-exists-snippet: snippets/sqs.xml
